version: "3.9"

services:

  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ideagram
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=sofeng-ideagram@1402
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:3.11.11-alpine"

    ports:
      - 5672:5672

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
    postgres-data:
    redis-data:

