# Generated by Django 4.1.7 on 2023-04-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_profilelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report_reasons', models.CharField(choices=[('spam', 'Spam'), ('promoting violence', 'Promoting Violence'), ('encouragement to commit suicide', 'Encouragement to commit suicide')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_profile', to='profiles.profile')),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_profile', to='profiles.profile')),
            ],
        ),
    ]
