# Generated by Django 4.1.7 on 2023-05-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilelinks'),
        ('ideas', '0004_collaborationrequest'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reasons', models.CharField(choices=[('spam', 'Spam'), ('promoting violence', 'Promoting Violence'), ('encouragement to commit suicide', 'Encouragement to commit suicide')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_idea', to='ideas.idea')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_idea', to='profiles.profile')),
            ],
        ),
    ]
