# Generated by Django 4.1.7 on 2023-04-13 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ideagram.common.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_profilelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=ideagram.common.utils.idea_upload_image_path)),
                ('attached_files_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('max_donation', models.PositiveIntegerField(default=0)),
                ('total_donation', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('show_likes', models.BooleanField(default=True)),
                ('show_views', models.BooleanField(default=True)),
                ('show_comments', models.BooleanField(default=True)),
                ('classification', models.ManyToManyField(to='ideas.classification')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
