# Generated by Django 4.1.7 on 2023-04-23 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('rial', 'rial'), ('dollar', 'dollar'), ('euro', 'euro')], max_length=20)),
                ('priority', models.PositiveSmallIntegerField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
            options={
                'unique_together': {('idea', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='EvolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('finish_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('priority', models.PositiveSmallIntegerField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
            options={
                'unique_together': {('idea', 'priority')},
            },
        ),
    ]
