# Generated by Django 4.1.7 on 2023-05-10 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_ideacomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('skills', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('salary', models.PositiveIntegerField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
        ),
    ]
