# Generated by Django 4.1.7 on 2023-05-12 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ideagram.common.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_collaborationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaAttachmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to=ideagram.common.utils.idea_upload_attachment_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
        ),
    ]
