# Generated by Django 4.1.7 on 2023-05-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_following'),
        ('ideas', '0005_ideaattachmentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_follower', to='profiles.profile')),
                ('profile_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_following', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile_id', 'idea_id')},
            },
        ),
    ]
