# Generated by Django 4.1.7 on 2023-05-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_following_idealikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
