# Generated by Django 4.1.7 on 2023-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('full_time', 'full_time'), ('part_time', 'part_time'), ('other', 'other')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
