# Generated by Django 4.1.7 on 2023-06-02 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_collaborationrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('register_number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.organization')),
            ],
        ),
    ]
