# Generated by Django 4.1.7 on 2023-04-09 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ideagram.common.utils
import ideagram.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128, unique=True, validators=[ideagram.profiles.validators.special_char_not_exist_validator])),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=15)),
                ('bio', models.CharField(blank=True, max_length=512, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=ideagram.common.utils.profile_upload_image_path)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('idea_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
