# Generated by Django 4.1.7 on 2023-04-09 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab'), ('telegram', 'telegram'), ('linkedin', 'linkedin'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('twitter', 'twitter')], max_length=15)),
                ('link', models.URLField(max_length=500)),
                ('priority', models.PositiveSmallIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'type')},
            },
        ),
    ]
