# Generated by Django 4.1.7 on 2023-05-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelinks',
            name='priority',
        ),
    ]
