# Generated by Django 4.1.7 on 2023-04-20 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('email_verification', 'email_verification'), ('password_reset', 'password_reset'), ('notification', 'notification')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.email')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
