# Generated by Django 4.1.7 on 2023-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentemail',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sentemail',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='sentemail',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
